/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-mixin-factory.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {EtoolsMixinFactory};

/**
 * Offers easier syntax for applying multiple mixins
 *
 * ```class EtoolsBehaviorsDemoHelper extends EtoolsMixinFactory.combineMixins([EtoolsLogsMixin], PolymerElement)```
 */
declare class EtoolsMixinFactory {
  static combineMixins(mixinsArray: any, superClass: any): any;
}
