/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-page-refresh-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';


/**
 * Cached page data refresh helper functionality
 */
declare function EtoolsPageRefreshMixin<T extends new (...args: any[]) => {}>(base: T): T & EtoolsPageRefreshMixinConstructor;

interface EtoolsPageRefreshMixinConstructor {
  new(...args: any[]): EtoolsPageRefreshMixin;
}

export {EtoolsPageRefreshMixinConstructor};

interface EtoolsPageRefreshMixin {
  dexieDbsNumber: number|null|undefined;
  dbsAttemptedToDelete: any[]|null|undefined;
  refreshInProgress: boolean|null|undefined;
  ready(): void;
  refresh(): void;
  clearLocalStorage(): void;
  clearDexieDbs(): void;
  deleteDexieDb(dbName: any): void;
  _refreshPage(): void;
  _triggerPageRefresh(deleteAttempts: any): void;
}
